version: '3.8'
services:
  app:
    container_name: express-mvc-tinkering
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run dev >> server.log 2>&1
